<img src="img/usmlogo.png" style="float:right;height:85px"> <img src="img/dilogo.png" style="float:left;height:90px">
<center>
    <h1> Laboratorio 2 </h1>
    <h2> Profesor: Ricardo Ñanculef y Francisco Mena </h2>
    <h3> Ayudante: Jorge Ludueña </h3>
    <h4> Alumno: Josué Venegas Almonacid; Rol: 201873534-5 </h4>
    <h5> Video: https://youtu.be/fdEfXPFQWio</h5>
</center>
<p>
<center><h4>2020-2</h4></center>
</p>

# Cadenas de Markov 

Las cadenas de markov son un modelo estocástico para describir una secuencia de sucesos donde la probabilidad de ir a un estado siguiente depende solamente del estado actual, esto se puede modelar de la siguiente forma:

$$ S_{n+1} = S_{n}\cdot P$$

Donde $P$ se conoce como matriz NxN de transición donde cada posicion $(i,j)$ se tiene que $P(i,j) = P(\text{estado }j|\text{estado }i)$ y $S_{n}$ los vectores N-dimensional de estado ($S_{0}$ es conocida). Una cadena de markov se dice regular si su matriz de transición es regular, esto quiere decir que alguna potencia de $P$ tiene todas sus entradas positivas (para este caso 0 no es positivo).

Si se tiene una cadena de markov regular, en algún momento de la secuencia se encontrará una matriz de estado tal que:

$$ S_{f} \cdot P = S_{f}$$ 

A este vector $S_{f}$ se le conoce como vector estacionario donde _f_ es el numero entero lo suficientemente grande para llegar al estado final.

## Comida rápida

Tres compañías de comida rápida están compitiendo por el primer lugar en la supremacía de comida rápida. 

* Si un cliente originalmente es fiel a "Paimon's Snack" tiene un $65\%$ de probabilidad de quedarse fiel a esta, un $20\%$ de cambiarse a "Completos NP" y un $15\%$ de cambiarse a "Little Pizza".

* Si un cliente originalmente es fiel a "Completos NP" tiene un $40\%$ de probabilidad de quedarse fiel a esta, un $30\%$ de cambiarse a "Paimon's Snack" y un $30\%$ de cambiarse a "Little Pizza".

* Si un cliente originalmente es fiel a "Little Pizza" tiene un $70\%$ de probabilidad de quedarse fiel a esta, un $10\%$ de cambiarse a "Paimon's Snack" y un $20\%$ de cambiarse a "Completos NP".

En un comienzo 200 clientes pertenecen a "Paimon's Snack", 180 a "Completos NP" y 20 a "Little Pizza".

>a) Identifique la matriz de transición y el vector de estado inicial

Podemos observar el enunciado a través de los siguientes gráficos:
<img src="img/datos.png" style="float:center;"> 

In [6]:
import numpy as np
matriz_transicion = np.array([
    [0.65, 0.20 ,0.15],
    [0.30, 0.40, 0.30],
    [0.10, 0.20, 0.70]
])
vector_inicial = np.array([0.50, 0.45, 0.05])

print(f"Matriz de transición: \n{matriz_transicion}\n")
print(f"Vector de estado inicial: {vector_inicial}")

Matriz de transición: 
[[0.65 0.2  0.15]
 [0.3  0.4  0.3 ]
 [0.1  0.2  0.7 ]]

Vector de estado inicial: [0.5  0.45 0.05]


>b) ¿Existirá la matriz estacionaria en este caso? Si su respuesta es sí, obténgala (en codigo).

_Hint: Utilice un criterio decimal de aproximación_

Para verificar si existe una matriz estacionaria, podemos iterar el proceso de multiplicar el vector de estado y la matriz de transición i-veces, con i un número muy grande. Luego, si el vector de estado resultante, al multiplicarlo una vez más con la matriz de transición, resulta en sí mismo, entonces la matriz estacionaria existe.

$$ S_{f} \cdot P = S_{f}$$ 

Otra opción para obtenerla es elevando la matriz de transición transpuesta i-veces, con i un número muy grande, y multiplicándolo con el vector de estado, como lo muestra la siguiente imagen:

<img src="img/formula.png" style="float:center;"> 

Notar que (a,b,c) puede ser cualquier vector de estado que cumpla la condición de que a+b+c = 1

In [7]:
# Sí. Una forma de calcular la matriz estacionaria es obteniendo el i-ésimo vector de estado, con i muy grande

#1 iteración
vector_resultante = np.matmul(vector_inicial, matriz_transicion)
print(f"El vector estado luego de la primera iteración es: \n{vector_resultante}\n")

#100 iteraciones
for i in range(100):
    vector_resultante = np.matmul(vector_resultante, matriz_transicion)
    
#Luego, en caso de ser estacionaria, el vector de estado multiplicado por la matriz de transición debería resultar en el mismo vector estado
print(f"El vector del estado i-ésimo es: \n{vector_resultante}\n")
print(f"Al multiplicarlo con la matriz de transición se obtiene: \n{np.matmul(vector_resultante, matriz_transicion)}\n")

#También se puede comprobar elevando la matriz transpuesta a un número grande y multiplicándolo por un vector estado cualquiera (cuyos valores sumen 1)
#de acuerdo a la figura presentada
from numpy.linalg import matrix_power

transpuesta = np.transpose(matriz_transicion)
transpuesta_i = matrix_power(transpuesta, 100)
vector_estado_i = np.matmul(transpuesta_i, vector_inicial)

print(f"Matriz i-ésima: \n {transpuesta_i}\n")
print(f"Vector estado i-ésimo a través del método de la matriz transpuesta i-ésima: \n{vector_estado_i}\n")

#Por lo que el vector estacionario es [0.33333333 0.25 0.41666667]

El vector estado luego de la primera iteración es: 
[0.465 0.29  0.245]

El vector del estado i-ésimo es: 
[0.33333333 0.25       0.41666667]

Al multiplicarlo con la matriz de transición se obtiene: 
[0.33333333 0.25       0.41666667]

Matriz i-ésima: 
 [[0.33333333 0.33333333 0.33333333]
 [0.25       0.25       0.25      ]
 [0.41666667 0.41666667 0.41666667]]

Vector estado i-ésimo a través del método de la matriz transpuesta i-ésima: 
[0.33333333 0.25       0.41666667]



>c) Después de pasado mucho tiempo. ¿Quién tendrá una mayor cantidad de clientes? Asuma que la matriz de transición será válida por todo este periodo arbitrario de tiempo y no llegarán ni saldrán más clientes del mundo de comida rápida. **No realice esta simulación como una multiplicación de matrices**, use las probabilidades y las cantidades dadas. Compare con b) 

Podemos calcular la probabilidad de la primera iteración en base a un árbol de decisiones:

<img src="img/arbol.png" style="float:center;"> 

Sin embargo si queremos obtener la probabilidad después de mucho tiempo, debemos resolver el sistema de ecuaciones siguiente:

<img src="img/sistema.png" style="float:center;"> 

In [14]:
# La probabilidad de que los clientes prefieran a PS, CNP, LP será la suma de todas las probabilidades correspondientes:

#1 iteración
probabilidad_pc = (0.50*0.65)+(0.45*0.30)+(0.05*0.10)
probabilidad_cnp = (0.45*0.40)+(0.50*0.20)+(0.05*0.20)
probabilidad_lp = (0.05*0.70)+(0.50*0.15)+(0.45*0.30)
primera_iteracion = np.array([probabilidad_pc, probabilidad_cnp, probabilidad_lp])
print(f"Primera iteración: \n {primera_iteracion}")

#Muchas iteraciones
#Para calcular la probabilidad después de mucho tiempo, tendremos que resolver el sistema lineal Ax = B donde A es la matriz cuadrada
#conformada por las las primeras dos filas de la matriz de transición y la tercera es la condición de que la suma de los elementos del vector
#estado inicial es 1

#Matriz transición:
#0,65x + 0,3y + 0,1z = x
#0,2x + 0,4y + 0,2z = y
#0,1x +0,2y + 0,7z = z

#Matriz A:
#-0,35x + 0,3y + 0,1z = 0
#0,2x + -0,6y + 0,2z = 0
#x + y + z = 1

print("\nMatriz transición: \n", matriz_transicion)
print("\nVector estado inicial: \n", vector_inicial)

canonica = np.array([[1,0,0], [0,1,0], [0,0,1]])
matriz_A = np.subtract(transpuesta, canonica)
matriz_A[2:] = [1,1,1]
print("\nMatriz A: \n", matriz_A)

vector_B = np.array([0,0,1])
print("\nVector B: \n", vector_B)

solucion = np.linalg.solve(matriz_A, vector_B)
print("\nSolución:\n", solucion)

#Obtenemos el mismo resultado que en b), es decir, el vector [0.33333333 0.25 0.41666667]
#Little Pizza tendrá la mayor cantidad de clientes (el 41,7% = 167 personas)

Primera iteración: 
 [0.465 0.29  0.245]

Matriz transición: 
 [[0.65 0.2  0.15]
 [0.3  0.4  0.3 ]
 [0.1  0.2  0.7 ]]

Vector estado inicial: 
 [0.5  0.45 0.05]

Matriz A: 
 [[-0.35  0.3   0.1 ]
 [ 0.2  -0.6   0.2 ]
 [ 1.    1.    1.  ]]

Vector B: 
 [0 0 1]

Solución:
 [0.33333333 0.25       0.41666667]


# Reglas del juego

- **Anote todas las supociciones que considere**
- El laboratorio es OPCIONAL se realiza de manera INDIVIDUAL y debe ser entregado en jupyter notebook utilizando Python3.
- Se debe subir un video con la explicacion del experimento (no solo de los resultados) en alguna plataforma de video y adjuntarlo el link al comienzo de este archivo, el cual debe ser entregado en Aula a mas tardar el sabado 3 de Octubre.
- Para obtener el bono debe obtener una nota mayor 54.
- Se responderán dudas solamente vía Aula.
- No se aceptaran laboratorios entregados fuera de plazo.

Si desea profundizar más:
- [MC 1](https://www.youtube.com/watch?v=uvYTGEZQTEs)
- [MC 2](https://www.youtube.com/watch?v=jtHBfLtMq4U)
- [MC 3](https://www.youtube.com/watch?v=P8DuuiINAo4&t)
- [MC 4](https://www.youtube.com/watch?v=31X-M4okAI0)
- [MC 5](https://www.youtube.com/watch?v=-kwnnNSGFMc)